-- verifying counts
SELECT count(*)
FROM ACTOR; -- 199
SELECT count(*)
FROM CATEGORY; -- 16
SELECT count(*)
FROM CITY; -- 600
SELECT count(*)
FROM CLASSIFICATION; -- 5
SELECT count(*)
FROM CLIENT; -- 599
SELECT count(*)
FROM EMPLOYEE; -- 2
SELECT count(*)
FROM STORE_INVENTORY; -- 1521
SELECT count(*)
FROM LANGUAGE; -- 6
SELECT count(*)
FROM COUNTRY; -- 109
SELECT count(*)
FROM MOVIE; -- 1000
SELECT count(*)
FROM MOVIE_ACTOR; -- 5462
SELECT count(*)
FROM MOVIE_LANGUAGE; -- 1000
SELECT count(*)
FROM MOVIE_CATEGORY; -- 1000
SELECT count(*)
FROM MOVIE_RENTAL; -- 16044 (16045)
SELECT count(*)
FROM STORE; -- 2
