SELECT count(*) FROM ACTOR; -- 199
SELECT count(*) FROM CATEGORY; -- 16
SELECT count(*) FROM CITY; -- 600
SELECT count(*) FROM CLASSIFICATION; -- 5
SELECT count(*) FROM CLIENT; -- 601 ?
SELECT count(*) FROM ADDRESS; -- 605 ?
SELECT count(*) FROM EMPLOYEE; -- 2
SELECT count(*) FROM STORE_INVENTORY; -- 1914 -- CORRECT = 1521
SELECT count(*) FROM LANGUAGE; -- 6
SELECT count(*) FROM COUNTRY; -- 109
SELECT count(*) FROM MOVIE; -- 1000
SELECT count(*) FROM MOVIE_ACTOR; -- 5432
SELECT count(*) FROM MOVIE_LANGUAGE; -- 1000
SELECT count(*) FROM MOVIE_CATEGORY; -- 1000
SELECT count(*) FROM RENTAL_BILL; -- 16078 -- CORRECT = 16044
SELECT count(*) FROM STORE; -- 2