-- Load data into tables-

-- TABLE COUNTRY
    (select distinct COUNTRY_CLIENT
    from TEMPORAL_TABLE
    WHERE COUNTRY_CLIENT NOT IN ('-'))
UNION
    (
    select distinct STORE_COUNTRY
    from TEMPORAL_TABLE
    WHERE STORE_COUNTRY NOT IN ('-')
)
UNION
    (select distinct EMPLOYEE_COUNTRY
    from TEMPORAL_TABLE
    WHERE EMPLOYEE_COUNTRY NOT IN ('-'));

-- CITIES
    (
    SELECT DISTINCT STORE_CITY as city
    FROM TEMPORAL_TABLE
    WHERE STORE_CITY NOT IN '-'
UNION
    SELECT DISTINCT CITY_CLIENT
    FROM TEMPORAL_TABLE
    WHERE CITY_CLIENT NOT IN '-');

-- STORE ADDRESS
SELECT DISTINCT STORE_ADDRESS, STORE_COUNTRY
FROM TEMPORAL_TABLE
WHERE STORE_ADDRESS
NOT IN '-';

-- CLIENT ADDRESS
SELECT DISTINCT CLIENT_ADDRESS, COUNTRY_CLIENT
FROM TEMPORAL_TABLE
WHERE CLIENT_ADDRESS NOT IN ('-');

-- filter registers without '-'
select count(*)
from (select distinct *
    from TEMPORAL_TABLE
    where STORE_CITY NOT IN '-');

-- filter registers with '-'
select count(*)
from (select distinct *
    from TEMPORAL_TABLE
    where STORE_CITY = '-');

-- zip code client
SELECT DISTINCT ZIP_CODE_CLIENT
FROM TEMPORAL_TABLE
WHERE ZIP_CODE_CLIENT NOT IN ('-');


-- store name
SELECT DISTINCT STORE_NAME, STORE_ADDRESS
FROM TEMPORAL_TABLE
WHERE NOT TEMPORAL_TABLE.STORE_NAME IN ('-');


-- clients
SELECT distinct CLIENT_NAME, CLIENT_EMAIL, ZIP_CODE_CLIENT, CREATION_DATE, FAVORITE_STORE, CLIENT_IS_ACTIVE
FROM TEMPORAL_TABLE
WHERE CLIENT_NAME
not in '-';

-- Employees
SELECT DISTINCT EMPLOYEE_NAME,
    EMPLOYEE_ADDRESS,
    EMPLOYEE_ZIP_CODE,
    EMPLOYEE_EMAIL,
    EMPLOYEE_USERNAME,
    EMPLOYEE_PASSWORD,
    EMPLOYEE_STORE,
    EMPLOYEE_IS_ACTIVE
FROM TEMPORAL_TABLE
where EMPLOYEE_NAME
not in '-';

-- Actors/Actress
SELECT DISTINCT MOVIE_ACTOR
FROM TEMPORAL_TABLE
WHERE MOVIE_ACTOR
NOT IN '-';

-- Actors/Actress (with movies)
SELECT DISTINCT MOVIE_ACTOR, MOVIE_NAME
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_ACTOR, MOVIE_NAME
ORDER BY MOVIE_NAME ASC;


-- Movies
SELECT DISTINCT MOVIE_NAME, MOVIE_DESCRIPTION, MOVIE_DURATION, RELEASE_YEAR, RENT_DAYS, RENT_COST, COST_PER_DAMAGE
FROM TEMPORAL_TABLE;

-- MOVIES WITH COUNT
-- Movies
SELECT MOVIE_NAME, STORE_NAME, count(*) AS veces
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_NAME, STORE_NAME;

-- Bridge
SELECT MOVIE_NAME, STORE_NAME, count(*) AS units
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_NAME, STORE_NAME;


SELECT MOVIE_NAME, count(*)
FROM TEMPORAL_TABLE
where MOVIE_NAME = 'SUGAR WONKA'
GROUP BY MOVIE_NAME;


-- Movie classification
SELECT DISTINCT CLASSIFICATION
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- Movie category
SELECT DISTINCT MOVIE_CATEGORY
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- Movie Language
SELECT DISTINCT MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE TEMPORAL_TABLE.MOVIE_LANGUAGE
NOT IN '-';

-- Movie with languages
SELECT DISTINCT MOVIE_NAME, MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
group by MOVIE_NAME, MOVIE_LANGUAGE
order by MOVIE_NAME asc;

-- Movie Rental
SELECT PAY_DATE, RETURN_DATE, PAY_DATE, EMPLOYEE_NAME
FROM TEMPORAL_TABLE;

----------------------------

SELECT DISTINCT STORE_NAME, STORE_ADDRESS, STORE_CITY, STORE_COUNTRY
FROM TEMPORAL_TABLE
WHERE STORE_NAME
NOT IN '-';

---
-- BILL
SELECT distinct CLIENT.CLIENT_NAME,
    TO_DATE(SALE_DATE, 'DD/MM/YYYY HH24:MI'),
    TO_DATE(PAY_DATE, 'DD/MM/YYYY HH24:MI'),
    EMPLOYEE.EMPLOYEE_CODE
FROM TEMPORAL_TABLE,
    CLIENT,
    EMPLOYEE
WHERE TEMPORAL_TABLE.CLIENT_NAME = CLIENT.CLIENT_NAME
    AND TEMPORAL_TABLE.EMPLOYEE_NAME = EMPLOYEE.EMPLOYEE_NAME;

select *
from EMPLOYEE;
