-- Inserting into countries table
INSERT INTO COUNTRY
    (COUNTRY_NAME)
    (select distinct COUNTRY_CLIENT
    from TEMPORAL_TABLE
    WHERE COUNTRY_CLIENT NOT IN ('-'))
UNION
    (
    select distinct STORE_COUNTRY
    from TEMPORAL_TABLE
    WHERE STORE_COUNTRY NOT IN ('-')
)
UNION
    (select distinct EMPLOYEE_COUNTRY
    from TEMPORAL_TABLE
    WHERE EMPLOYEE_COUNTRY NOT IN ('-'));


-- Insert into table CITY (from city_client)
INSERT INTO CITY
    (CITY_NAME, FK_COUNTRY_CODE)
    (SELECT distinct CITY_CLIENT, COUNTRY.COUNTRY_CODE
    FROM TEMPORAL_TABLE,
        COUNTRY
    where COUNTRY_CLIENT = COUNTRY.COUNTRY_NAME)
union
    (
    SELECT distinct STORE_CITY, COUNTRY_CODE
    FROM TEMPORAL_TABLE,
        COUNTRY
    WHERE STORE_COUNTRY = COUNTRY.COUNTRY_NAME
)
union
    (
    SELECT distinct EMPLOYEE_CITY, COUNTRY_CODE
    FROM TEMPORAL_TABLE,
        COUNTRY
    WHERE EMPLOYEE_COUNTRY = COUNTRY.COUNTRY_NAME
);