-- Inserting into countries table
INSERT INTO COUNTRY
     (COUNTRY_NAME)
     (select distinct COUNTRY_CLIENT
     from TEMPORAL_TABLE
     WHERE COUNTRY_CLIENT NOT IN ('-'))
UNION
     (
    select distinct STORE_COUNTRY
     from TEMPORAL_TABLE
     WHERE STORE_COUNTRY NOT IN ('-')
)
UNION
     (select distinct EMPLOYEE_COUNTRY
     from TEMPORAL_TABLE
     WHERE EMPLOYEE_COUNTRY NOT IN ('-'));


-- Insert into table CITY (from city_client)
INSERT INTO CITY
     (CITY_NAME, FK_COUNTRY_CODE)
     (SELECT distinct CITY_CLIENT, COUNTRY.COUNTRY_CODE
     FROM TEMPORAL_TABLE,
          COUNTRY
     where COUNTRY_CLIENT = COUNTRY.COUNTRY_NAME)
union
     (
    SELECT distinct STORE_CITY, COUNTRY_CODE
     FROM TEMPORAL_TABLE,
          COUNTRY
     WHERE STORE_COUNTRY = COUNTRY.COUNTRY_NAME
)
union
     (
    SELECT distinct EMPLOYEE_CITY, COUNTRY_CODE
     FROM TEMPORAL_TABLE,
          COUNTRY
     WHERE EMPLOYEE_COUNTRY = COUNTRY.COUNTRY_NAME
);


-- INSERT INTO ADDRESS TABLE
INSERT INTO ADDRESS
     (ADDRESS_NAME, FK_CITY_CODE)
     (SELECT DISTINCT CLIENT_ADDRESS, CITY_CODE
     FROM TEMPORAL_TABLE,
          CITY
     WHERE CITY_CLIENT = CITY.CITY_NAME
          AND CLIENT_ADDRESS NOT IN '-'
    )
UNION
     (
    SELECT DISTINCT STORE_ADDRESS, CITY_CODE
     FROM TEMPORAL_TABLE,
          CITY
     WHERE STORE_CITY = CITY.CITY_NAME
          AND STORE_ADDRESS NOT IN '-'
)
UNION
     (
    SELECT DISTINCT EMPLOYEE_ADDRESS, CITY_CODE
     FROM TEMPORAL_TABLE,
          CITY
     WHERE EMPLOYEE_CITY = CITY.CITY_NAME
          AND EMPLOYEE_ADDRESS NOT IN '-'
);

-- INSERT INTO STORE TABLE
INSERT INTO STORE
     (STORE.STORE_NAME, STORE.FK_ADDRESS_CODE)
SELECT DISTINCT STORE_NAME, ADDRESS_CODE
FROM TEMPORAL_TABLE,
     ADDRESS
WHERE NOT TEMPORAL_TABLE.STORE_NAME IN ('-')
     AND TEMPORAL_TABLE.STORE_ADDRESS = ADDRESS.ADDRESS_NAME;

-- INSERT INTO CLIENT TABLE
INSERT INTO CLIENT
     (CLIENT_FIRST_NAME, CLIENT_LAST_NAME, CLIENT_ZIP_CODE, CLIENT_EMAIL, REGISTER_DATE, CLIENT_STATE,
     ADDRESS_CODE,
     FAVORITE_STORE_CODE)
SELECT distinct (SELECT REGEXP_SUBSTR(CLIENT_NAME, '[^ ]+', 1, 1)
     FROM DUAL)      as client_first_name,
     (SELECT REGEXP_SUBSTR(CLIENT_NAME, '[^ ]+', 1, 2)
     FROM DUAL)      as client_last_name,
     ZIP_CODE_CLIENT,
     CLIENT_EMAIL,
     TO_DATE(CREATION_DATE, 'dd/mm/yyyy'),
     CLIENT_IS_ACTIVE,
     ADDRESS.ADDRESS_CODE,
     STORE.STORE_CODE as fav_store
FROM TEMPORAL_TABLE,
     ADDRESS,
     STORE
WHERE CLIENT_NAME
not in '-'
  and TEMPORAL_TABLE.CLIENT_ADDRESS = ADDRESS_NAME
  AND TEMPORAL_TABLE.FAVORITE_STORE = STORE.STORE_NAME;

select *
from CLIENT;

-- INSERTING INTO CLASSIFICATION TABLE
INSERT INTO CLASSIFICATION
     (CLASSIFICATION_NAME)
SELECT DISTINCT CLASSIFICATION
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- INSERTING INTO CATEGORY TABLE
INSERT INTO CATEGORY
     (CATEGORY_NAME)
SELECT DISTINCT MOVIE_CATEGORY
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- INSERTING INTO LANGUAGE TABLE
INSERT INTO LANGUAGE
     (LANGUAGE_NAME)
SELECT DISTINCT MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE TEMPORAL_TABLE.MOVIE_LANGUAGE
NOT IN '-';

-- INSERTING INTO MOVIES TABLE
INSERT INTO MOVIE
     (MOVIE_TITLE, MOVIE_DESCRIPTION, MOVIE_DURATION, RELEASE_YEAR, RENT_TIME, RENT_COST, PENALTY_COST,
     CLASSIFICATION_CODE, CATEGORY_CODE, LANGUAGE_CODE)
SELECT DISTINCT MOVIE_NAME,
     MOVIE_DESCRIPTION,
     MOVIE_DURATION,
     RELEASE_YEAR,
     RENT_DAYS,
     RENT_COST,
     COST_PER_DAMAGE,
     CLASSIFICATION.CLASSIFICATION_CODE,
     CATEGORY.CATEGORY_CODE,
     LANGUAGE.LANGUAGE_CODE
FROM TEMPORAL_TABLE,
     CLASSIFICATION,
     CATEGORY,
     LANGUAGE
WHERE TEMPORAL_TABLE.CLASSIFICATION = CLASSIFICATION.CLASSIFICATION_NAME
     AND TEMPORAL_TABLE.MOVIE_CATEGORY = CATEGORY.CATEGORY_NAME
     AND TEMPORAL_TABLE.MOVIE_LANGUAGE = LANGUAGE.LANGUAGE_NAME
     AND TEMPORAL_TABLE.MOVIE_NAME
NOT IN '-';


-- INSERTING INTO ACTOR TABLES
INSERT INTO ACTOR
     (ACTOR_FIRST_NAME, ACTOR_LAST_NAME)
SELECT DISTINCT (SELECT REGEXP_SUBSTR(MOVIE_ACTOR, '[^ ]+', 1, 1)
     FROM DUAL) as actor_first_name,
     (SELECT REGEXP_SUBSTR(MOVIE_ACTOR, '[^ ]+', 1, 2)
     FROM DUAL) as actor_last_name
FROM TEMPORAL_TABLE
WHERE MOVIE_ACTOR
NOT IN '-';

-- INSERTING INTO MOVIE_DETAIL
INSERT INTO MOVIE_DETAIL
     (MOVIE_CODE, ACTOR_CODE)
SELECT distinct MOVIE.MOVIE_CODE, ACTOR.ACTOR_CODE
FROM TEMPORAL_TABLE,
     ACTOR,
     MOVIE
WHERE TEMPORAL_TABLE.MOVIE_ACTOR = ACTOR.ACTOR_FIRST_NAME || ' ' || ACTOR.ACTOR_LAST_NAME
     AND TEMPORAL_TABLE.MOVIE_NAME = MOVIE.MOVIE_TITLE;

select *
from MOVIE_DETAIL;


-- INSERTING INTO store_INVENTORY
select *
from STORE_INVENTORY;

INSERT INTO STORE_INVENTORY
     (MOVIE_CODE, STORE_CODE, AVAILABLE_INVENTORY)

SELECT MOVIE.MOVIE_CODE, STORE.STORE_CODE, COUNT(*) AS available_inventory
FROM TEMPORAL_TABLE,
     MOVIE,
     STORE
WHERE TEMPORAL_TABLE.MOVIE_NAME = MOVIE.MOVIE_TITLE
     AND TEMPORAL_TABLE.STORE_NAME = STORE.STORE_NAME
GROUP BY MOVIE.MOVIE_CODE, STORE.STORE_CODE
ORDER BY MOVIE_CODE;


-- INSERTING INTO EMPLOYEES
INSERT INTO EMPLOYEE
     (EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_ADDRESS, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME,
     EMPLOYEE_PASSWORD,
     EMPLOYEE_STATE, STORE_CODE)
SELECT DISTINCT (SELECT REGEXP_SUBSTR(EMPLOYEE_NAME, '[^ ]+', 1, 1)
     FROM DUAL) as first_name,
     (SELECT REGEXP_SUBSTR(EMPLOYEE_NAME, '[^ ]+', 1, 2)
     FROM DUAL) as last_name,
     EMPLOYEE_ADDRESS,
     EMPLOYEE_EMAIL,
     EMPLOYEE_USERNAME,
     EMPLOYEE_PASSWORD,
     EMPLOYEE_IS_ACTIVE,
     STORE.STORE_CODE
FROM TEMPORAL_TABLE,
     STORE
where TEMPORAL_TABLE.EMPLOYEE_STORE = STORE.STORE_NAME
     AND EMPLOYEE_NAME
not in '-';

-- Load data into tables-

-- TABLE COUNTRY
     (select distinct COUNTRY_CLIENT
     from TEMPORAL_TABLE
     WHERE COUNTRY_CLIENT NOT IN ('-'))
UNION
     (
    select distinct STORE_COUNTRY
     from TEMPORAL_TABLE
     WHERE STORE_COUNTRY NOT IN ('-')
)
UNION
     (select distinct EMPLOYEE_COUNTRY
     from TEMPORAL_TABLE
     WHERE EMPLOYEE_COUNTRY NOT IN ('-'));

-- CITIES
     (
     SELECT DISTINCT STORE_CITY as city
     FROM TEMPORAL_TABLE
     WHERE STORE_CITY NOT IN '-'
UNION
     SELECT DISTINCT CITY_CLIENT
     FROM TEMPORAL_TABLE
     WHERE CITY_CLIENT NOT IN '-');

-- STORE ADDRESS
SELECT DISTINCT STORE_ADDRESS, STORE_COUNTRY
FROM TEMPORAL_TABLE
WHERE STORE_ADDRESS
NOT IN '-';

-- CLIENT ADDRESS
SELECT DISTINCT CLIENT_ADDRESS, COUNTRY_CLIENT
FROM TEMPORAL_TABLE
WHERE CLIENT_ADDRESS NOT IN ('-');

-- filter registers without '-'
select count(*)
from (select distinct *
     from TEMPORAL_TABLE
     where STORE_CITY NOT IN '-');

-- filter registers with '-'
select count(*)
from (select distinct *
     from TEMPORAL_TABLE
     where STORE_CITY = '-');

-- zip code client
SELECT DISTINCT ZIP_CODE_CLIENT
FROM TEMPORAL_TABLE
WHERE ZIP_CODE_CLIENT NOT IN ('-');


-- store name
SELECT DISTINCT STORE_NAME, STORE_ADDRESS
FROM TEMPORAL_TABLE
WHERE NOT TEMPORAL_TABLE.STORE_NAME IN ('-');


-- clients
SELECT distinct CLIENT_NAME, CLIENT_EMAIL, ZIP_CODE_CLIENT, CREATION_DATE, FAVORITE_STORE, CLIENT_IS_ACTIVE
FROM TEMPORAL_TABLE
WHERE CLIENT_NAME
not in '-';

-- Employees
SELECT DISTINCT EMPLOYEE_NAME,
     EMPLOYEE_ADDRESS,
     EMPLOYEE_ZIP_CODE,
     EMPLOYEE_EMAIL,
     EMPLOYEE_USERNAME,
     EMPLOYEE_PASSWORD,
     EMPLOYEE_STORE,
     EMPLOYEE_IS_ACTIVE
FROM TEMPORAL_TABLE
where EMPLOYEE_NAME
not in '-';

-- Actors/Actress
SELECT DISTINCT MOVIE_ACTOR
FROM TEMPORAL_TABLE
WHERE MOVIE_ACTOR
NOT IN '-';

-- Actors/Actress (with movies)
SELECT DISTINCT MOVIE_ACTOR, MOVIE_NAME
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_ACTOR, MOVIE_NAME
ORDER BY MOVIE_NAME ASC;


-- Movies
SELECT DISTINCT MOVIE_NAME, MOVIE_DESCRIPTION, MOVIE_DURATION, RELEASE_YEAR, RENT_DAYS, RENT_COST, COST_PER_DAMAGE
FROM TEMPORAL_TABLE;

-- MOVIES WITH COUNT
-- Movies
SELECT MOVIE_NAME, STORE_NAME, count(*) AS veces
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_NAME, STORE_NAME;

-- Bridge
SELECT MOVIE_NAME, STORE_NAME, count(*) AS units
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
GROUP BY MOVIE_NAME, STORE_NAME;


SELECT MOVIE_NAME, count(*)
FROM TEMPORAL_TABLE
where MOVIE_NAME = 'SUGAR WONKA'
GROUP BY MOVIE_NAME;


-- Movie classification
SELECT DISTINCT CLASSIFICATION
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- Movie category
SELECT DISTINCT MOVIE_CATEGORY
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION
NOT IN '-';

-- Movie Language
SELECT DISTINCT MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE TEMPORAL_TABLE.MOVIE_LANGUAGE
NOT IN '-';

-- Movie with languages
SELECT DISTINCT MOVIE_NAME, MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE MOVIE_NAME
NOT IN '-'
group by MOVIE_NAME, MOVIE_LANGUAGE
order by MOVIE_NAME asc;

-- Movie Rental
SELECT PAY_DATE, RETURN_DATE, PAY_DATE, EMPLOYEE_NAME
FROM TEMPORAL_TABLE;

----------------------------

SELECT DISTINCT STORE_NAME, STORE_ADDRESS, STORE_CITY, STORE_COUNTRY
FROM TEMPORAL_TABLE
WHERE STORE_NAME
NOT IN '-';

---
-- BILL
INSERT INTO RENTAL_BILL
     (RENTAL_DATE, PAY_DATE, CLIENT_CODE, EMPLOYEE_CODE)
SELECT distinct TO_DATE(SALE_DATE, 'DD/MM/YYYY HH24:MI') AS RENTAL_DATE,
     TO_DATE(PAY_DATE, 'DD/MM/YYYY HH24:MI')  AS PAY_DATE,
     CLIENT.CLIENT_CODE,
     EMPLOYEE.EMPLOYEE_CODE
FROM TEMPORAL_TABLE,
     CLIENT,
     EMPLOYEE
WHERE TEMPORAL_TABLE.CLIENT_NAME = CLIENT.CLIENT_FIRST_NAME || ' ' || CLIENT.CLIENT_LAST_NAME
     AND TEMPORAL_TABLE.EMPLOYEE_NAME = EMPLOYEE.EMPLOYEE_FIRST_NAME || ' ' || EMPLOYEE.EMPLOYEE_LAST_NAME;

-- INSERT MASTER_DETAIL TABLE
INSERT INTO DETAIL_BILL
     (RENTAL_CODE, MOVIE_CODE, RETURN_DATE, RENT_COST)
SELECT DISTINCT RENTAL_BILL.RENTAL_CODE,
     MOVIE.MOVIE_CODE,
     TO_DATE(TEMPORAL_TABLE.RETURN_DATE, 'DD/MM/YYYY HH24:MI'),
     TEMPORAL_TABLE.MOUNT_TO_PAY
FROM TEMPORAL_TABLE,
     RENTAL_BILL,
     MOVIE
WHERE TEMPORAL_TABLE.SALE_DATE = to_char(RENTAL_BILL.RENTAL_DATE, 'DD/MM/YYYY HH24:MI')
     AND TEMPORAL_TABLE.PAY_DATE = to_char(RENTAL_BILL.PAY_DATE, 'DD/MM/YYYY HH24:MI')
     and TEMPORAL_TABLE.MOVIE_NAME = MOVIE.MOVIE_TITLE
     and TEMPORAL_TABLE.SALE_DATE
not in '-'
  and TEMPORAL_TABLE.PAY_DATE not in '-'
  and TEMPORAL_TABLE.RETURN_DATE not in '-';

