-- Inserting into countries table
INSERT INTO COUNTRY
    (COUNTRY_NAME)
    (select distinct COUNTRY_CLIENT
     from TEMPORAL_TABLE
     WHERE COUNTRY_CLIENT NOT IN ('-'))
UNION
(
    select distinct STORE_COUNTRY
    from TEMPORAL_TABLE
    WHERE STORE_COUNTRY NOT IN ('-')
)
UNION
(select distinct EMPLOYEE_COUNTRY
 from TEMPORAL_TABLE
 WHERE EMPLOYEE_COUNTRY NOT IN ('-'));


-- Insert into table CITY (from city_client)
INSERT INTO CITY (CITY_NAME, FK_COUNTRY_CODE)
    (SELECT distinct CITY_CLIENT, COUNTRY.COUNTRY_CODE
     FROM TEMPORAL_TABLE,
          COUNTRY
     where COUNTRY_CLIENT = COUNTRY.COUNTRY_NAME)
union
(
    SELECT distinct STORE_CITY, COUNTRY_CODE
    FROM TEMPORAL_TABLE,
         COUNTRY
    WHERE STORE_COUNTRY = COUNTRY.COUNTRY_NAME
)
union
(
    SELECT distinct EMPLOYEE_CITY, COUNTRY_CODE
    FROM TEMPORAL_TABLE,
         COUNTRY
    WHERE EMPLOYEE_COUNTRY = COUNTRY.COUNTRY_NAME
);


-- INSERT INTO ADDRESS TABLE
INSERT INTO ADDRESS (ADDRESS_NAME, FK_CITY_CODE)
    (SELECT DISTINCT CLIENT_ADDRESS, CITY_CODE
     FROM TEMPORAL_TABLE,
          CITY
     WHERE CITY_CLIENT = CITY.CITY_NAME
       AND CLIENT_ADDRESS NOT IN '-'
    )
UNION
(
    SELECT DISTINCT STORE_ADDRESS, CITY_CODE
    FROM TEMPORAL_TABLE,
         CITY
    WHERE STORE_CITY = CITY.CITY_NAME
      AND STORE_ADDRESS NOT IN '-'
)
UNION
(
    SELECT DISTINCT EMPLOYEE_ADDRESS, CITY_CODE
    FROM TEMPORAL_TABLE,
         CITY
    WHERE EMPLOYEE_CITY = CITY.CITY_NAME
      AND EMPLOYEE_ADDRESS NOT IN '-'
);

-- INSERT INTO STORE TABLE
INSERT INTO STORE (STORE.STORE_NAME, STORE.FK_ADDRESS_CODE)
SELECT DISTINCT STORE_NAME, ADDRESS_CODE
FROM TEMPORAL_TABLE,
     ADDRESS
WHERE NOT TEMPORAL_TABLE.STORE_NAME IN ('-')
  AND TEMPORAL_TABLE.STORE_ADDRESS = ADDRESS.ADDRESS_NAME;

-- INSERT INTO CLIENT TABLE
INSERT INTO CLIENT(CLIENT_NAME, CLIENT_ZIP_CODE, CLIENT_EMAIL, REGISTER_DATE, CLIENT_STATE, ADDRESS_CODE,
                   FAVORITE_STORE_CODE)
SELECT distinct CLIENT_NAME,
                ZIP_CODE_CLIENT,
                CLIENT_EMAIL,
                TO_DATE(CREATION_DATE, 'dd/mm/yyyy'),
                CLIENT_IS_ACTIVE,
                ADDRESS.ADDRESS_CODE,
                STORE.STORE_CODE as fav_store
FROM TEMPORAL_TABLE,
     ADDRESS,
     STORE
WHERE CLIENT_NAME not in '-'
  and TEMPORAL_TABLE.CLIENT_ADDRESS = ADDRESS_NAME
  AND TEMPORAL_TABLE.FAVORITE_STORE = STORE.STORE_NAME;

select *
from CLIENT;

-- INSERTING INTO CLASSIFICATION TABLE
INSERT INTO CLASSIFICATION (CLASSIFICATION_NAME)
SELECT DISTINCT CLASSIFICATION
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION NOT IN '-';

-- INSERTING INTO CATEGORY TABLE
INSERT INTO CATEGORY (CATEGORY_NAME)
SELECT DISTINCT MOVIE_CATEGORY
FROM TEMPORAL_TABLE
WHERE CLASSIFICATION NOT IN '-';

-- INSERTING INTO LANGUAGE TABLE
INSERT INTO LANGUAGE(LANGUAGE_NAME)
SELECT DISTINCT MOVIE_LANGUAGE
FROM TEMPORAL_TABLE
WHERE TEMPORAL_TABLE.MOVIE_LANGUAGE NOT IN '-';

-- INSERTING INTO MOVIES TABLE
INSERT INTO MOVIE (MOVIE_TITLE, MOVIE_DESCRIPTION, MOVIE_DURATION, RELEASE_YEAR, RENT_TIME, RENT_COST, PENALTY_COST,
                   CLASSIFICATION_CODE, CATEGORY_CODE, LANGUAGE_CODE)
SELECT DISTINCT MOVIE_NAME,
                MOVIE_DESCRIPTION,
                MOVIE_DURATION,
                RELEASE_YEAR,
                RENT_DAYS,
                RENT_COST,
                COST_PER_DAMAGE,
                CLASSIFICATION.CLASSIFICATION_CODE,
                CATEGORY.CATEGORY_CODE,
                LANGUAGE.LANGUAGE_CODE
FROM TEMPORAL_TABLE,
     CLASSIFICATION,
     CATEGORY,
     LANGUAGE
WHERE TEMPORAL_TABLE.CLASSIFICATION = CLASSIFICATION.CLASSIFICATION_NAME
  AND TEMPORAL_TABLE.MOVIE_CATEGORY = CATEGORY.CATEGORY_NAME
  AND TEMPORAL_TABLE.MOVIE_LANGUAGE = LANGUAGE.LANGUAGE_NAME
  AND TEMPORAL_TABLE.MOVIE_NAME NOT IN '-';


-- INSERTING INTO ACTOR TABLES
INSERT INTO ACTOR (ACTOR_NAME)
SELECT DISTINCT MOVIE_ACTOR
FROM TEMPORAL_TABLE
WHERE MOVIE_ACTOR NOT IN '-';
