-- create temp table
CREATE TABLE temporal_table
(
    client_name        varchar2(50),
    client_email       varchar2(50),
    client_is_active   varchar2(50),
    creation_date      varchar2(50),
    favorite_store     varchar2(50),
    client_address     varchar2(50),
    zip_code_client    varchar2(50),
    city_client        varchar2(50),
    country_client     varchar2(50),
    sale_date          varchar2(50),
    return_date        varchar2(50),
    mount_to_pay       varchar2(50),
    pay_date           varchar2(50),
    employee_name      varchar2(50),
    employee_email     varchar2(50),
    employee_is_active varchar2(50),
    employee_store     varchar2(50),
    employee_username  varchar2(50),
    employee_password  varchar2(50),
    employee_address   varchar2(50),
    employee_zip_code  varchar2(50),
    employee_city      varchar2(50),
    employee_country   varchar2(50),
    store_name         varchar2(50),
    store_manager      varchar2(50),
    store_address      varchar2(50),
    store_zip_code     varchar2(50),
    store_city         varchar2(50),
    store_country      varchar2(50),
    movie_store        varchar2(50),
    movie_name         varchar2(50),
    movie_description  varchar2(50),
    release_year       varchar2(50),
    rent_days          varchar2(50),
    rent_cost          varchar2(50),
    movie_duration     varchar2(50),
    cost_per_damage    varchar2(50),
    classification     varchar2(50),
    movie_language     varchar2(50),
    movie_category     varchar2(50),
    movie_actor        varchar2(50)
);