/*
1. Mostrar la cantidad de copias que existen en el inventario para la película
“Sugar Wonka”.
*/

SELECT SUM(STORE_INVENTORY.AVAILABLE_INVENTORY) AS VECES
FROM STORE_INVENTORY
    JOIN MOVIE M on M.MOVIE_CODE = STORE_INVENTORY.MOVIE_CODE
WHERE M.MOVIE_CODE = (SELECT MOVIE_CODE
FROM MOVIE
WHERE MOVIE_TITLE = 'SUGAR WONKA');
